### ISSUE TITLE
[TXT] Damage Feed Text Output Error for Masterwork Old Spear

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOR_Core_old#34]
**Describe the text issue**
When the Masterwork Old Spear deals damage, it is output to the damage feed without a space between the number and damage type.  This was also visisble with other weapons such as the Ridged Tipped Arming Sword from Native.

**Screenshots**
See the following [screenshots](https://imgur.com/a/LIa6UH1), accompanying [video](https://streamable.com/wwh5xp) and [save game](https://drive.google.com/drive/folders/1jpfsSPzt1zi6n0tkgfASGhtzoHaaTdYG?usp=sharing).

Although this is a text issue, it may be more suited to be recorded as a bug.

**Comment by Z3rca** [comment]
done in damsel branch
