### ISSUE TITLE
[BUG] Crash in Wurtbad Tournament Arena on Successful Kick

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOR_Core_old#37]
**Describe the bug**
A crash in Wurtbad Tournament arena when kicking an opponent and it landing sucessfully.

**To Reproduce**
1. Load [save](https://drive.google.com/file/d/1zC3xlCtF0xNIdD0TNPjJ9AmPYMTkDIwW/view?usp=drive_link)
2. Fight in Tournanment
3. Kick opponent.

**Times Reproduced**
3 / 3 times reproduced each time with sword and shield (this is a statement about how bad I am with 2H weapons and my inability to trigger it whilst holding a 2H weapon, not that it did not trigger.)

**Expected behavior**
Kick resolves as normal - stagger / damage application.

**Screenshots**
Video [here](https://streamable.com/7pc8ft).

**Crash Dump**
[Here](https://drive.google.com/file/d/1VYHhqZwCs605wlbK41QoYxysThzz2zHL/view?usp=drive_link).

**Comment by hunharibo** [comment]
Fixed with e4b593d
