### ISSUE TITLE
[TXT] Missing Text for "haunted_site_3" North West of Krugenheim / South East of Talabheim

### ISSUE THREAD

**Issue by debarr1** [TheOldRealms/TOR_Core_old#38]
**Describe the text issue**
The left hand panel menu that pops up when entering settlements for the haunted site North West of Krugenheim / South East of Talabheim is missing text.

**Where to find?**
Approach the haunted site, North West of Krugenheim  / South East of Talabheim as a non magic using Empire of Man character.

**Notes and Warnings**
"ERROR: Text with id customsettlement_into doesn't exist! Variation: haunted_site_03"

**Screenshots**
[Here](https://imgur.com/a/QblA1DE).

**Comment by Z3rca** [comment]
I believe this cursed site has a name anyway
