### ISSUE TITLE
[TXT] The Hanged Men inky

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOR_Core_old#45]
**Describe the text issue**
Raise the hanging bodies as skeletons ( +3zombies,Mercy--), It first talks about skeletons, yet it would give zombies?

**Where to find?**
The Hanged Men inky

**Screenshots**
![Schermafbeelding 2023-08-11 185309](https://github.com/TheOldRealms/TOR_Core/assets/63518948/98b776f9-379d-4b10-b576-8a396ed45be2)

**Comment by Z3rca** [comment]
solved long time ago
