### ISSUE TITLE
[TXT] Two words joined in the article on de Brionne (Quenelles).

### ISSUE THREAD

**Issue by Pierogolepca** [TheOldRealms/TOR_Core_old#46]
**Describe the text issue**
The Encyclopedia entry on Brionne (which is actually Quenelles) contains a text issue "pillagedestroy". Pretty sure it's supposed to be just "pillage" as per the Bretonnia google doc.

**Where to find?**
Encyclopedia -> Clans -> de Brionne (1st entry, there are two and the 1st one actually refers to Quenelles) -> 2nd line.

**Screenshots**
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/5668148b-ec25-4f45-8364-db24a801ed9e)

**Comment by Z3rca** [comment]
thank you , I wouldn't have catched this mistake of the clan naming.... lol ....
