### ISSUE TITLE
[TXT] Text issues in the Lore of Life spells

### ISSUE THREAD

**Issue by Pierogolepca** [TheOldRealms/TOR_Core_old#47]
**Describe the text issue**
1. Summer Heat: the description is not clear "making them" -> "making the enemies".
2. Summer Heat: the description is missing the duration, just says "for  seconds".
3. Drain Life: the description is missing the spell duration and a full stop at the end.
4. Barkskin: the description contains a typo "provding" -> "providing".
5. Barkskin: the description is missing the spell duration and a full stop at the end.
6. Regrowth: the description is missing a full stop at the end.
7. Dwellers Below: the description is missing the spell duration, it only says "...dmg per second for (insert spell duration)".
8. Storm of Renewal: the description is missing the spell duration, it only says "...inside the area for (insert spell duration)".

**Where to find?**
Spellbook -> Lore of Life

**Screenshots**
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/f9fbb54a-9d1e-4f80-9230-ea885b8f23f6)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/d6995e74-4fcc-49e4-8944-1600335eb8a3)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/f17e4d65-332a-48ac-b051-5a57aa41d167)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/257e204a-9e47-4b21-b759-8e1390af7c82)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/404e3b82-0a2a-4c1a-a5b0-ef9d87be29c3)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/e654eafa-2dc1-45f2-93ac-f868a57bad8a)

**Comment by Z3rca** [comment]
Done Thanks Ecthelion

**Comment by Pierogolepca** [comment]
Not fixed yet
