### ISSUE TITLE
[TXT] Text issues in the Lore of Beasts spells

### ISSUE THREAD

**Issue by Pierogolepca** [TheOldRealms/TOR_Core_old#48]
Describe the text issue

1. Tangling Thorn and Hail Storm are sharing the same description (tho one seems to be using the older version).
2. Pann's Pelt and The Beast Unleashed are sharing the same description.
3. Flock of Doom: the description is missing a full stop at the end.
4. Curse of Anraheir: the description contains a typo "secodnds" -> "seconds".
5. Curse of Anraheir: the description is missing the damage value, it only says "...small damage over time (how much damage)".
6. Curse of Anraheir: the description is unclear when it comes to duration - first it says "for seconds" and then "for (3/s)" at the end. This formatting suggests it's 3 damage per second but the description also contains a place holder so I assume it's about the duration. In that case it should be "for 3s). Imo Curse of Anraheir should be rewritten from scratch to be more clear because it's kinda jumbled.

Where to find?
Spellbook -> Lore of Beasts

Screenshots
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/e6e25340-5458-48a6-bb84-483d586d073f)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/06b172e7-66d4-4d95-904c-e91d3d65aad4)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/ae4054b3-b430-43b2-9377-9ece95ceecd0)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/53c20dd9-25c0-44bd-ac32-3ae4aefc938c)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/a9fce01b-cae6-420a-b7e1-bb041edaad68)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/63ed0c70-93f8-4008-be1f-6b078a467a96)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/c0502278-9426-48c8-ae3f-57c60cf01d8a)

**Comment by Z3rca** [comment]
Done Thanks Ecthelion

**Comment by Pierogolepca** [comment]
Not fixed

**Comment by Z3rca** [comment]
see defect text issues (83c23c9758a43c3f867815369daed67491755059)
