### ISSUE TITLE
[TXT] Text issues in the game - Von Carstein career 

### ISSUE THREAD

**Issue by Pierogolepca** [TheOldRealms/TOR_Core_old#51]
**Describe the text issue**
A set of text issues regarding the Von Carstein career and my suggestions on how to fix, make them clear(er) or more consistent. None of my suggestions should be exceeding the character limit for perks. If I skip any perks, that means those are good to go.

**Where to find?**
Create a vampire character -> Select Von Carstein Vampire at the start -> Go to the Career menu

1. Career ability (broken into separate paragraphs to make this report more readable):
- The Vampire transforms into a fog, that is impossible to catch and can fly wherever the player wants. -> The player transforms into fog, which is impossible to catch and can fly in every direction.
- The Ability lasts for 5 seconds. The duration can be increased for each point in athletics by 0.03 seconds. ->The ability lasts 5 seconds and the duration increases by 0.03 seconds for each point in Athletics.
- The Mistform can be deactivated at will, by pressing attack. ->Mist Form can be deactivated at will by pressing attack.
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/26a13724-e99b-4404-963e-0965d620bf7f)

2. New Blood:
- Increaes Partysize by 25 -> Increases Party size by 25.
- Immune to sunlight speed malus -> Immune to sunlight speed malus.
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/4fc2b0dc-0787-4e3d-b4d4-769ca01f1ff8)

3. The Arkayne:
- Increases Winds of Magic by 10. -> Increases max Winds of Magic by 10.
- Extra Magical Spell Damage(10%). -> Increases Magical spell damage by 10%.
- Extra Magical melee Damage(10%). -> 10% extra Magical melee damage.
- 10% Cost reduction for spells -> 10% cost reduction for spells.
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/9c6a4de9-63c6-48c1-ae59-869aab83892f)

4. The Courtley:
- Increases positive relationship gains by 20% -> Increases positive Relation gains by 20%.
- Extra Magical Spell and Ranged Damage(10%). -> 10% extra Magical spell and ranged damage.
- Killing Blows targeted to the Head replenish 3 Winds of Magic -> Killing blows in the head replenish 3 Winds of Magic.
- Mistform is loaded on battle start. Roguery counts towards mistform enchancement. -> Mist Form is recharged on battle start and now also scales with Roguery.
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/98ea592e-2936-4e0a-bb91-afde5b58a54d)

5. The Lordly:
- Partyspeed Increased by 1.5 -> Party movement speed is increased by 1.5.
- Increases Partysize by 75. -> Party size is increased by 75.
- Wages for Vampires are reduced by 15% -> All Vampire troops wages are reduced by 15%.
- Upgrade costs are halfed -> Upgrade costs are halved.
- Mistform heals 3 HP per second. Your wielded weapon is counted towards the ability duration. -> Mist Form heals 3 HP per second. The ability duration scales with the wielded weapon skill.
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/e5eff5db-9a9e-4817-bf6a-6dd1e2e68331)

6. The Martialle:
- Extra Melee Damage(10%). -> 10% extra melee damage.
- 10% Extra damage for all troops against humans -> All troops gain 10% extra damage against human enemies.
- All attacks deal bonus damage against shields -> All attacks deal bonus damage against shields.
- Swing speed increases by 20%, buffs are active after Mistform. Requires extra 30% damage. -> +20% swing speed. Buffs are active after Mist Form (requires extra 30% damage dealt).
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/791ceebc-a017-4c12-8a66-9fe21f2c6957)

7. Master of Dead -> Master of the Dead (the name needs "**the**" between "of" and "Dead":
- Increases Partysize by 100. -> Increases Party size by 100.
- Undead units get 25% Wardsave Resistance -> Undead troops gain 25% Ward save.
- 20% Higher chance for raised dead after battle -> 20% higher chance for raised dead after battle.
- Tier 4 Undead troops can get 'wounded' with a 20% lower chance -> Tier 4 Undead troops can get wounded with a 20% lower chance.
- All buffs are propagated when Mistform. Requires extra 30% damage dealt. -> All buffs are propagated while remaining in Mist Form (requires extra 30% damage dealt).
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/9113b2b3-c163-474b-9139-f7ce25a42be2)

**Comment by Pierogolepca** [comment]
This is now fixed, thank you.

**Comment by Pierogolepca** [comment]
Sorry, forgot about these two minor issues (career ability description):
-     the arrow > symbol is still around
-     missing space in the ability description (before "Mist Form", last sentence)
![image](https://github.com/TheOldRealms/TOR_Core/assets/141856223/234cd553-d76c-46e8-83e7-d91bee3ed896)

**Comment by Z3rca** [comment]
![image](https://github.com/TheOldRealms/TOR_Core/assets/43908801/e8063380-fe12-4a9a-8118-97fa85aebe08)
