### ISSUE TITLE
[TXT] Walach Harkon improper vassalage text

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOR_Core_old#55]
**Describe the text issue**
When trying to join the Blood Keep as a vassal, there is an ERROR text id issue

**Where to find?**
Talk to Walach Harkon to join the Blood Keep as a vassal

**Notes and Warnings**
ERROR: text with id tor_feudal_oath_line1 doesnt exist

**Screenshots**
![Schermafbeelding 2023-08-29 082531](https://github.com/TheOldRealms/TOR_Core/assets/63518948/806f8250-c71f-4785-b5bf-09bd9436003b)

**Comment by Z3rca** [comment]
fixed
