### ISSUE TITLE
[TXT] Walach Harkon introduces himself as ruler of Sylvania

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOR_Core_old#56]
**Describe the text issue**
When talking to Walach Harkon he introduces himself as ruler of Sylvania

**Where to find?**
Walach Harkon conversation

**Screenshots**
![Schermafbeelding 2023-08-29 082348](https://github.com/TheOldRealms/TOR_Core/assets/63518948/2ed1e4eb-f4ed-4af5-aa43-9e7a8068e82f)

**Comment by Z3rca** [comment]
fixed
