### ISSUE TITLE
[TXT] Mannfred double text option issue

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOR_Core_old#57]
**Describe the text issue**
When asking Mannfred for a bloodkiss, there are 2 duplicate options

**Where to find?**
Talking to Mannfred, asking him for the bloodkiss

**Additional context**
Walach Harkon bloodkiss conversation states that you'll become a "Blood Knight", i would suggest doing the same in Mannfred's case that you'll become a "Von Carstein" vampire.

**Screenshots**
![Schermafbeelding 2023-08-29 201349](https://github.com/TheOldRealms/TOR_Core/assets/63518948/77e9e769-79e5-49ec-b34c-7588942278f5)

**Comment by Z3rca** [comment]
fixed
