### ISSUE TITLE
[BUG] Hideout boss battle headshot crash

### ISSUE THREAD

**Issue by R4MPZY** [TheOldRealms/TOR_Core_old#7]
**Describe the bug**
I was provided a save file for a hideout battle where you don't do anything, let your troops do the small mobs and when the boss spawns, accept duel and headshot him results in an instant crash

**To Reproduce**
1. Go to 'bandit hideout with a firearm'
2. Click on 'attack and accept duel vs the hideout boss'
3. See error

**Times Reproduced**
3/3

**Expected behavior**
Headshot the hideout boss and get my well earned loots ;)

crash logs with save file[here](https://drive.google.com/file/d/18pHFp0GUG-HTJglCypykUgMjbHHAlC5h/view?usp=sharing) and video [here](https://streamable.com/idh3gh)

**Comment by Z3rca** [comment]
Might be related to the "alert" mechanic removed a long time ago. The hideout mission was over, however the script was still looking for an entity and caused the crash. however , the problem does not occur anymore, so we can for now just close it.

Retested doesn't occur anymore
