### ISSUE TITLE
[IMPROVEMENT] i18n support

### ISSUE THREAD

**Issue by CartierPierre** [TheOldRealms/TOR_Core_old#87]
Hello,  
To look forward in the future, it would be great to have some translations of the texts. Actually, strings seems to be in many separate files, making very hard a translation contribution.  
Is there any project file structuration to accept i18n standart ?  
For exemple, in Django (python), we can put the texts file in `<app>/locale/<lang>/strings.xyz`, and then to do easy translation, we can just take the all english file; put it in a GenAI assistant and translate very easy in like 10 other languages.  
Maybe something natively supported by C# ? https://stackoverflow.com/questions/12862407/i18n-c-sharp-application  

By making this, it's easier to translate, and easier to follow the main development without impacting your features.
If it's too complicated (I have no idea how hard is to develop a mod), you can just close the issue 😄 
Bye

**Comment by Z3rca** [comment]
we have our own translation method for it. once the first translations are working we will provide an easy way for translation for public available for all languages.
