### ISSUE TITLE
[BUG] TOR Shader Game Manager

### ISSUE THREAD

**Issue by Cheyron** [TheOldRealms/TOR_Core_old#89]
**Describe the bug**
Implementing logic from TORShaderGameManager and receiving a null object exception in CustomBattle.StartGame.

**To Reproduce**
1. Copy class to ADOD project.
2. Update TOR character objects to ADOD equivalents.
3. Add InitialStateOption to load this game manager, inheriting, CustomGameManager
4. Crash in LoadScene, CustomBattle.GameStart

**Times Reproduced**
100%

**Expected behavior**
CustomBattleData appears to be setup correctly, it selected a player character and created the player and enemy party. I expected the game to start in custom battle and load shaders.

**Screenshots**
[Game Manager](https://imgur.com/3z4T7wR)

**Additional context**
I am your #1 fan. TOR Team Rocks!

**Comment by hunharibo** [comment]
I am happy to help as much as I can on discord to solve your issue, but this bug report is not directly TOR related, so allow me to close it. Accept my friend request on discord and let's talk.
